// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__HelloController from "./bridge/hello_controller"
application.register("bridge--hello", Bridge__HelloController)
